import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(public)/_components/layout/Header";
import Footer from "./(public)/_components/layout/Footer";
import GlobalContextProvider from "@/providers/GlobalContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <GlobalContextProvider>
        <body className={inter.className}>
          <Header />

          {children}
          <Footer />
        </body>
      </GlobalContextProvider>
    </html>
  );
}
